name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
# clone this repository
git clone git@github.com:mac-s-g/github-help-wanted.git && cd github-help-wanted
# install dependencies
npm install
# run the dev server at http://localhost:3100/
npm run build
# copy build resources to /dist/
cp ./src/images/favicon.ico README.md CNAME ./dist/
